### ISSUE TITLE
please readd the initial data/rogcore.conf 

### ISSUE THREAD

**Issue by aspann** [flukejones/rog-core#26]
Hi @flukejones,

between 13.1 and 14.0 you removed the initial config. could you be so kind and readd it into the next release, otherwise it breaks the gentoo ebuild.. (you know that config replacement thingy - for now, I'll use (again) my own until it is available again)

cheers.

**Comment by flukejones** [comment]
Can you try with adding a blank file? I removed the default because it will change for each laptop and having a default with all LED modes won't work correctly.

**Comment by aspann** [comment]
check - works.
