### ISSUE TITLE
G532LW support

### ISSUE THREAD

**Issue by andreihabalau** [flukejones/rog-core#32]
@devs thank you for the great work on this software.

I edited the laptops.rs file and can confirm that all led modes work at the level of GX502.
Everything else worked properly on this machine, except for the fan toggle (but I don't have a kernel version with the patches you mentioned, so I wasn't really expecting it to work).

Can you please add G532 to the supported models list?

**Comment by flukejones** [comment]
Done

**Comment by andreihabalau** [comment]
@flukejones you've added G532 to the wrong section and now the RGB control doesn't work any more. It should be the same as GX502 not GU502.

**Comment by flukejones** [comment]
F A C E P A L M

**Comment by flukejones** [comment]
That should be fixed. If not you can reopen this.
