### ISSUE TITLE
Silent fan profile does not persist on GA401

### ISSUE THREAD

**Issue by schaerfo** [flukejones/rog-core#36]
After applying the 'silent' fan profile with
```
$ rog-core -f silent
```
the fan spin down, but only for a few seconds. After that, they return to their normal speed.
In order to have the fans in silent mode continuously, the command above has to be run periodically.

**Comment by Yarn** [comment]
The "normal" speeds they return to are still the silent profile (and should be a bit lower than the normal profile). I have custom fan curves working if you want to beta test that, I don't have the instructions anywhere but on the discord (linked in the readme) atm though.

**Comment by schaerfo** [comment]
OK, that is some rather unintuitive behavior then. I will perhaps take a look at the custom fan curves, thanks!
