### ISSUE TITLE
Allow changing fan modes from cmdline/dbus

### ISSUE THREAD

**Issue by dragonnn** [flukejones/rog-core#7]
I think it would be nice to add more commands available via the rog-core cmdline like setting fan mode.
This would allow us to make more integration with some DE/WM.

**Comment by flukejones** [comment]
Done.

**Comment by dragonnn** [comment]
Works, cosmetic changes, description is wrong:
  -f, --fan-mode FAN  <off, low, med, high>

**Comment by flukejones** [comment]
🤦‍♂️
