### ISSUE TITLE
Setting turbo/boost on AMD gives an error

### ISSUE THREAD

**Issue by dragonnn** [flukejones/rog-core#9]
```
[ERROR] Could not write to /sys/devices/system/cpu/cpufreq/boost, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
```
I think it means it is writing wrong value?
BTW. it would be fine to also allow setting no_turbo to for example "ignore" or "donotchange" or just comment it out.

**Comment by flukejones** [comment]
From what I was reading about it, you can just write a 0 or 1 to it? It might be a case of it expecting a 1 as a char... I'll do a quick fix for you to check.

**Comment by dragonnn** [comment]
0 or 1 but as char

**Comment by flukejones** [comment]
Got it. Will fix shortly, easy fix.

**Comment by flukejones** [comment]
[Pre-release here](https://github.com/flukejones/rog-core/releases/tag/v0.9.9)

**Comment by dragonnn** [comment]
Works now, thank you. Did you think about the "ignore" option? I wrote my own program for creating power management profiles: https://gitlab.com/dragonn/rog-watcher it is still pretty basic but works like I like it.
